version: '3'
services:
  zabbix-timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: zabbix-timescaledb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:centos-5.0.3
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-timescaledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '10051:10051'
    links:
      - zabbix-timescaledb
    depends_on:
      - zabbix-timescaledb
  zabbix-web:
    image: zabbix/zabbix-web-apache-pgsql:centos-5.0.3
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-timescaledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ZBX_SERVER_HOST: "zabbix-server"
      PHP_TZ: Asia/Shanghai
    ports:
      - '80:8080'
      - '443:443'
    links:
      - zabbix-timescaledb
      - zabbix-server
    depends_on:
      - zabbix-timescaledb
      - zabbix-server
